base_url = "https://semanticdata.github.io/profile-card"
title = "Zola Profile Card"
description = "A simple profile card for Zola."
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false
